module.exports = {
    beforeEach: browser => {
        browser.url('https://alpha.yoodlize.com/')
    },
    after: browser => {
        browser.end()
    },
    'Navigate each see all link': browser => {
        browser
            .useXpath()
            .click("//div[contains(text(), 'See all')]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'category: Recreational Vehicles')
            .click("//img")
            .click("(//div[contains(text(), 'See all')])[2]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'category: Outdoor Gear')
            .click("//img")
            .click("(//div[contains(text(), 'See all')])[3]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'category: Electronics')
            .click("//img")
            .click("(//div[contains(text(), 'See all')])[4]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'category: Party & Wedding Equipment')
            .click("//img")
            .click("(//div[contains(text(), 'See all')])[5]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'category: Tools')
            .click("//img")
            .click("(//div[contains(text(), 'See all')])[6]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'category: Clothing')
            .click("//img")
            .click("(//div[contains(text(), 'See all')])[7]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'category: Home and Kitchen')
            .click("//img")
            .click("(//div[contains(text(), 'See all')])[8]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'category: Toys and Games')
            .click("//img")
            .click("(//div[contains(text(), 'See all')])[9]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'category: Lawn and Garden')
            .click("//img")
            .click("(//div[contains(text(), 'See all')])[10]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'category: Sporting Equipment')
            .click("//img")
            .click("(//div[contains(text(), 'See all')])[11]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'category: DVDs')
            .click("//img")
            .click("(//div[contains(text(), 'See all')])[12]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'category: Venues')
            .click("//img")
            .click("(//div[contains(text(), 'See all')])[13]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'category: Music')
            .click("//img")
            .click("(//div[contains(text(), 'See all')])[14]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'category: Business Equipment')
            .click("//img")
            .click("(//div[contains(text(), 'See all')])[15]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'category: Misc')
            .click("//img")
    },
    'Very each category at bottom of page under browse categories is clickable, navigable and takes users to correct page': browser => {
        browser
            .useXpath()
            .click("//div[@class = 'sc-jqCOkK MvxJP sc-gqjmRU ksayja']")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'category: Tools')
            .click("//img")
            .click("(//div[@class = 'sc-jqCOkK MvxJP sc-gqjmRU ksayja'])[2]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'Outdoor Gear')
            .click("//img")
            .click("(//div[@class = 'sc-jqCOkK MvxJP sc-gqjmRU ksayja'])[3]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'Electronics')
            .click("//img")
            .click("(//div[@class = 'sc-jqCOkK MvxJP sc-gqjmRU ksayja'])[4]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'Party & Wedding Equipment')
            .click("//img")
            .click("(//div[@class = 'sc-jqCOkK MvxJP sc-gqjmRU ksayja'])[5]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'Recreational Vehicles')
            .click("//img")
            .click("(//div[@class = 'sc-jqCOkK MvxJP sc-gqjmRU ksayja'])[6]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'Clothing')
            .click("//img")
            .click("(//div[@class = 'sc-jqCOkK MvxJP sc-gqjmRU ksayja'])[7]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'Home and Kitchen')
            .click("//img")
            .click("(//div[@class = 'sc-jqCOkK MvxJP sc-gqjmRU ksayja'])[8]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'Toys and Games')
            .click("//img")
            .click("(//div[@class = 'sc-jqCOkK MvxJP sc-gqjmRU ksayja'])[9]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'Lawn and Garden')
            .click("//img")
            .click("(//div[@class = 'sc-jqCOkK MvxJP sc-gqjmRU ksayja'])[10]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'Sporting Equipment')
            .click("//img")
            .click("(//div[@class = 'sc-jqCOkK MvxJP sc-gqjmRU ksayja'])[11]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'DVDs')
            .click("//img")
            .click("(//div[@class = 'sc-jqCOkK MvxJP sc-gqjmRU ksayja'])[12]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'Venues')
            .click("//img")
            .click("(//div[@class = 'sc-jqCOkK MvxJP sc-gqjmRU ksayja'])[13]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'Music')
            .click("//img")
            .click("(//div[@class = 'sc-jqCOkK MvxJP sc-gqjmRU ksayja'])[14]")
            .assert.containsText("//div[@class = 'sc-jKVCRD jSqgxr']", 'Misc')
            .click("//img")
    }
}